name: 'Auto Translate Readme'

description: 'Automatically translate the language of README via Github Action'

author: 'https://github.com/Lin-jun-xiang'

branding:
  icon: "book-open"
  color: "red"

inputs:
  token:
    description: 'Secrets Token to authorize bot account'
    required: true
  langs:
    description: 'Languages for README'
    required: true

runs:
      using: "composite"
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 3
            token: ${{ inputs.token }}
            zhipuai: ${{ inputs.zhipuai }}

        - name: Set Up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'

        - name: Install Dependencies
          shell: bash
          run: |
            pip install PyExecJS
            pip install -U g4f
            pip install -U zhipuai
            pip install --upgrade tenacity

        - name: Translate README
          shell: bash
          working-directory: .
          run: |
            export LANGS=${{ inputs.langs }}
            python $GITHUB_ACTION_PATH/translation.py

        - name: Git Commit
          shell: bash
          working-directory: .
          run: |
            git config --global user.email "username@users.noreply.github.comm";
            git config --global user.name "Continuous Integration"

            chmod +x $GITHUB_ACTION_PATH/commit.sh
            bash $GITHUB_ACTION_PATH/commit.sh
