name: Translate Readme

on:
  push:
    branches: ['**']

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Test my action
        uses: ./
        with:
          token: ${{ secrets.Action_Bot }} # Your token
          zhipuai: ${{ secrets.zhipuai_api_key }} # Optional: Your zhipuai api key if use zhipuai
          openai: ${{ secrets.openai_api_key }}  # Optional: Your openai api key if use openai
          langs: "en,zh-TW,zh-CN,French" # You can define any langs
