name: Translate Readme

on:
  push:
    branches: ['**']

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Test my action
        uses: ./
        with:
          token: ${{ secrets.Action_Bot }} # Your token
          zhipuai: ${{ secrets.zhipuai_api_key }} # Your zhipuai api key if use zhipuai instead of g4f
          langs: "en,zh-TW,zh-CN,French,Arabic" # You can define any langs
